[project]
name = "islamopedia-books"
version = "0.1.0"
description = "The project is a collection of books on Islam."
authors = [
    { name = "Gul Shair Butt", email = "segullshairbutt@gmail.com" },
]
requires-python = ">=3.9,<4.0"
dependencies = [
    "jupyter-book>=2.1.6,<3.0.0",
]

[tool.uv]
package = false
